### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by joostlek** [joostlek/python-spotify#306]
- [x] `current_user_followed_artists`
- [x] `current_user_saved_albums`
- [x] `current_user_saved_tracks`
- [x] `current_user_saved_shows`
- [x] `current_user_recently_played`
- [x] `current_user_top_artists`
- [x] `current_user_top_tracks`
- [x] `featured_playlists`
- [x] `categories`
- [x] `category_playlists`
- [x] `new_releases`
- [x] `playlist`
- [x] `album`
- [x] `artist_albums`
- [x] `artist`
- [x] `show_episodes`
- [x] `show`
- [ ] Checking how everything can work nicely in the media browser
